# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/"
  to = "/docs.json"
  status = 301

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "index.json"
    [headers.values]
      # 72 hours
      cache-control = '''
      public,
      max-age=259200'''

[[headers]]
  for = "*.html"
    [headers.values]
      # 72 hours
      cache-control = '''
      public,
      max-age=259200'''
